import HomeContent from "./home-content";
import Footer from "./footer";
import Hero from "./hero";
import Loading from "./loading";
import NavBar from "./nav-bar";
import VacanciesContent from "./vacancies-content";
import CandidatesContent from "./candidates-content";
import InterviewsContent from "./interviews-content";
import ProfileContent from "./profile-content";
import ScreenCaptureContent from "./screen-capture-content";
export { HomeContent, VacanciesContent, CandidatesContent, InterviewsContent, ProfileContent,ScreenCaptureContent, Footer, Hero, Loading, NavBar };
